language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_f7e0a4265448_key -iv $encrypted_f7e0a4265448_iv
  -in aws_django.pem.enc -out aws_django.pem -d
install: pip install -r requirements.txt
script: pytest -v --cov . --cov-report term-missing --flake8
deploy:
  provider: script
  script: fab -i aws_django.pem -H ubuntu@13.53.121.83 deploy
  on:
    branch: master
